"use client";

import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "./ThemeProvider";
import { ToastProvider } from "./ToastProvider";
import { LoaderProvider } from "./LoaderProvider";
import { Amplify } from "aws-amplify";
// @ts-ignore - This file is generated by Amplify after sandbox/deployment
import outputs from "../../amplify_outputs.json";

// Configure Amplify
try {
  Amplify.configure(outputs);
} catch (e) {
  console.warn("Amplify could not be configured. Make sure amplify_outputs.json exists.", e);
}

export default function Providers({ children }: { children: React.ReactNode }) {
  return (
    <SessionProvider>
      <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
        <ToastProvider>
          <LoaderProvider>
            {children}
          </LoaderProvider>
        </ToastProvider>
      </ThemeProvider>
    </SessionProvider>
  );
}
